# --- Required Project Identity ---
sonar.projectKey=securenet-parent-portal
sonar.projectName=SecureNet Parent Portal
sonar.projectVersion=1.0

# --- Paths and Language ---
# Tells SonarQube where your code lives
sonar.sources=app,scripts
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

# --- Exclusions (Clean up the report) ---
# We exclude infrastructure and environment files so they don't mess up your code score
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/terraform/**,**/k8s/**,**/docs/**,**/.env*,**/tests/**,**/node_modules/**

# --- Quality Gate ---
# This forces the Jenkins pipeline to wait for a "Pass" or "Fail" result
sonar.qualitygate.wait=true

# --- Logging & Analysis ---
# Useful for debugging if the scan fails
sonar.verbose=true
sonar.log.level=INFO
